### PR TITLE
changed background and text color in the footer

### PR DESCRIPTION
**Pull request by alexisCodeIn**
Good new coolor to impact. I like it.

### CODE REVIEW

**Review by AlejandroIbague — CHANGES_REQUESTED** [review]
I think that color will be so hard to the eyes for the readers. We can discuss it in the meeting tomorrow.

**Comment by alexisCodeIn** [comment]
like we discussed, the green will be better. Merge the change :)

**Comment by AlejandroIbague** [comment]
yesss thats it

**Review by AlejandroIbague — APPROVED** [review]
Green in the footer :)

**Pull request merged**
